/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.6.0/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
	`kotlin-dsl` // 必须启用，允许用 Kotlin 编写插件
	`maven-publish` // 引入发布插件

//    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
//    `java-gradle-plugin`

//    // Apply the Kotlin JVM plugin to add support for Kotlin.
//    alias(libs.plugins.kotlin.jvm)

//	//将插件发布到 Gradle 插件门户
//	alias(libs.plugins.gradle.plugin.publish)
}

kotlin {
	jvmToolchain(21)
}

repositories {
	//优先本地,国内
	mavenLocal()
	//maven("https://repo.spring.io/release")
	//maven("https://repo.huaweicloud.com/repository/maven/")
	//maven("https://mirrors.cloud.tencent.com/nexus/repository/maven-public/")

	// Use Maven Central for resolving dependencies.
	mavenCentral()
	gradlePluginPortal()
}

dependencies {
	// 引入你需要的外部插件作为依赖，供你的代码内部 apply
	implementation(libs.spring.boot.plugin)
	implementation(libs.spring.javaformat.plugin)
	implementation(libs.maven.publish.plugin)
}

gradlePlugin {
	website.set("https://github.com/rocg-cloud/rocg-gradle-plugin")
	vcsUrl.set("https://github.com/rocg-cloud/rocg-gradle-plugin.git")

	plugins {
		create("bomPlugin") {
			id = "io.github.rocwg.gradle.plugin.bom"
			implementationClass = "io.github.rocwg.gradle.plugin.BomPlugin"
			displayName = "BomPlugin"
			description = "bom or dependencies use"
			tags = listOf("bom", "dependencies")
		}
		create("modulePlugin") {
			id = "io.github.rocwg.gradle.plugin.module"
			implementationClass = "io.github.rocwg.gradle.plugin.ModulePlugin"
			displayName = "ModulePlugin"
			description = "Used to mark modules, all available nodes"
			tags = listOf("modules", "nodes")
		}
		create("commonPlugin") {
			id = "io.github.rocwg.gradle.plugin.common"
			implementationClass = "io.github.rocwg.gradle.plugin.CommonPlugin"
			displayName = "CommonPlugin"
			description = "The packaging method is ordinary jar instead of spring bootJar"
			tags = listOf("jar", "package")
		}
		create("rootProjectPlugin") {
			id = "io.github.rocwg.gradle.plugin.root"
			implementationClass = "io.github.rocwg.gradle.plugin.RootPlugin"
			displayName = "RootPlugin"
			description = "Used to mark certain root nodes to directly operate sub-packages"
			tags = listOf("rootNodes")
		}
		create("servicePlugin") {
			id = "io.github.rocwg.gradle.plugin.service"
			implementationClass = "io.github.rocwg.gradle.plugin.ServicePlugin"
			displayName = "ServicePlugin"
			description = "The packaging method is spring bootJar"
			tags = listOf("spring", "bootJar")
		}
		create("deployedPlugin") {
			id = "io.github.rocwg.gradle.plugin.mvn.deployed"
			implementationClass = "io.github.rocwg.gradle.plugin.maven.DeployedPlugin"
			displayName = "DeployedPlugin"
			description = "Used to deploy releases to MVN"
			tags = listOf("deploy", "maven")
		}
		create("JacocoExpand") {
			id = "io.github.rocwg.gradle.plugin.jacoco"
			implementationClass = "io.github.rocwg.gradle.plugin.tasks.JacocoExpandPlugin"
		}
	}
}

// 有什么用？
tasks.jar {
	manifest.attributes.putIfAbsent(
		"Created-By",
		"${System.getProperty("java.version")} (${System.getProperty("java.specification.vendor")})"
	)
	manifest.attributes.putIfAbsent("Gradle-Version", GradleVersion.current())
}

// 配置发布
publishing {
	publications {
		create<MavenPublication>("pluginMaven") {
			// 这里 Gradle 会自动帮你把 gradlePlugin 里的插件全部打包发布
		}
	}
	repositories {
		// 1. 动态获取环境变量中的 URL
		val snapshotUrl = providers.environmentVariable("ALIYUN_MAVEN_SNAPSHOT_URL").orNull
			?: providers.gradleProperty("aliyun_maven_snapshot_url").orNull
		val releaseUrl = providers.environmentVariable("ALIYUN_MAVEN_RELEASE_URL").orNull
			?: providers.gradleProperty("aliyun_maven_release_url").orNull

		// 2. 直接通过 project.version 拿到实值字符串，彻底避免被 Provider 包装误导
		val pluginVersion = project.version.toString()
		logger.lifecycle("[Build Logic] 插件版本: $pluginVersion")

		// 3. 智能判断（现在 pluginVersion 是真正的字符串了）
		val targetUrl = if (pluginVersion.endsWith("-SNAPSHOT")) snapshotUrl else releaseUrl
		logger.lifecycle("[Build Logic] 私有仓库: $targetUrl")

		if (!targetUrl.isNullOrBlank()) {
			maven {
				url = uri(targetUrl)
				credentials {
					username = providers.environmentVariable("ALIYUN_MAVEN_USERNAME").orNull
						?: providers.gradleProperty("aliyun_maven_username").orNull
					password = providers.environmentVariable("ALIYUN_MAVEN_PASSWORD").orNull
						?: providers.gradleProperty("aliyun_maven_password").orNull
				}
			}
		} else {
			// 可选：如果没配置私库，打印一条警告，防止团队其他成员迷茫
			logger.warn("⚠️ [Build Logic] 未检测到私有仓库 URL 配置，发布任务将失效！")
		}
	}
}
